**Example 1:Adding Two Lists vs Numpy Arrays**

In [1]:
import numpy as np

In [2]:
import time

In [5]:
#Python list
size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))
start = time.time()
result = [x + y for x, y in zip(list1, list2)]
end = time.time()
print("Python list additon time: ",end - start)

#Numpy array
arr1 = np.array(list1)
arr2 = np.array(list2)

start = time.time()
result = arr1 + arr2#Vectorized operation
end = time.time()
print("Numpy array addition time: ", end - start)

Python list additon time:  0.10274314880371094
Numpy array addition time:  0.01327967643737793


**creating NumPy Arrays**

In [6]:
import numpy as np

In [8]:
#creating 1D array
arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [9]:
#Creating a 2D array
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [10]:
#Checking type and shape

In [11]:
print("Type:", type(arr1))
print("shape: ",arr2.shape)

Type: <class 'numpy.ndarray'>
shape:  (2, 3)


- Numpy stores data in a contiguous memory block,making access faster than lists.
- shape shows the dimensions of an array.

**Memory Efficienct - Numpy vs Lists**

In [12]:
import sys

In [15]:
import sys

list_data = list(range(1000))
numpy_data = np.array(list_data)

print("Python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")
print("NumPy array size:", numpy_data.nbytes, "bytes")


Python list size: 9112000 bytes
NumPy array size: 4000 bytes


In [18]:
print("Python list size : ",sys.getsizeof(list_data) * len(list_data), "bytes")

Python list size :  9112000 bytes


- Numpy arrays use significantly less memory compared to python lists.