**indexing (Same as Python Lists)**

In [1]:
import numpy as pd

In [3]:
arr = pd.array([10,20,30,40])
print(arr[0])
print(arr[-1])

10
40


**Slicing(Extracting Parts of an array)**

In [4]:
arr = pd.array([10,20,30,40,50])
print(arr[1:4])

[20 30 40]


In [5]:
print(arr[:3])

[10 20 30]


In [6]:
print(arr[::2])

[10 30 50]


**Slicing returns a view, not a copy changes affect the original array**

this might seem counterintuitive since python  lists create copies when sliced. but in numpy,slicing returns a view of the original array.Both the sliced array and the original array share the same data in memory,so changes in the slice affect the original array.

this happens because - 
 - memory effeciancy : Avoid unnecessary copies,making operation faster and saving memory.
 - performance  : Enables faster access and manipulation of large datasets without duuplicating data.

In [8]:
sliced = arr[1:4]

In [9]:
sliced[0] = 999

In [10]:
print(arr)

[ 10 999  30  40  50]


**Fancy Indexing and Boolean Masking**

In [11]:
idx = [0,2,4]
print(arr[idx])

[10 30 50]


**Boolean Masking (Filter Data)**

In [12]:
arr = pd.array([10,20,30,40,50])
mask = arr > 25
print(arr[mask])

[30 40 50]
