**understanding Axes in numpy**


Each dimension in anumpy array is called axis.Axes are numbered starting from 0.
For example :
- 1D->1 axis(axis 0)
- 2D->2 axes(axis 0=rows,axis 1=columns)
- 3D->3 axes(axis 0=depth,axis 1=rows,axis 2=columns)

In [7]:
import numpy as np
arr= np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])

In [8]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Summing along axes:
    

In [9]:
print(np.sum(arr,axis=0))
print(np.sum(arr, axis=1))

[12 15 18]
[ 6 15 24]


**Indexing in multidimension Arrays**

In [11]:
print(arr[1,2]) # row index 1,column index 2

6


slicing

In [12]:
print(arr[0:2,1:3])

[[2 3]
 [5 6]]


**Indexing in 3D array,** 
the first index refers to the "depth" (sheets of data).

In [13]:
arr3D = np.array([[[1,2,3],[4,5,6]],
                  [[7,8,9],[10,11,12]]
                 ])
print(arr3D.shape)

(2, 2, 3)


In [15]:
#first sheet , second row, third column
print(arr3D[0,1,2])#output: 6
print(arr3D[:,0,:])#get the first row from both sheets

6
[[1 2 3]
 [7 8 9]]


**Practical Example: Selecting Data Along Axes**

In [16]:
#get all rows of the first column
first_col = arr[:,0]
print(first_col)

[1 4 7]


In [18]:
#get the first row from each "sheet" in a 3Darray
first_rows = arr3D[:,0,:]
print(first_rows)

[[1 2 3]
 [7 8 9]]


**Changing Data Along an Axes**

In [19]:
#Replace all elements in column 1 with 0
arr[:,1] = 0
print (arr)

[[1 0 3]
 [4 0 6]
 [7 0 9]]
