In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [4]:
np.mean(arr)

3.0

In [5]:
np.std(arr)

1.4142135623730951

In [6]:
np.var(arr)

2.0

In [7]:
np.exp(arr)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [8]:
np.log(arr)


array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [9]:
np.linspace(0, 10, 5) 

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [10]:
np.cumsum(arr)

array([ 1,  3,  6, 10, 15], dtype=int32)